name: Python write output
on:
    workflow_dispatch: {}
    push:
        branches: main
        paths: .github/workflows/py_write-output.yml
jobs:
    py-write-output:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Python
              uses: actions/setup-python@v7
              with:
                python-version: '3.13'
            - name: Python Write output
              id: write
              shell: python
              run: |
                import os
                print("Hello world")
                print("::error:: This is a test error from Python")
                print("::warning:: This is a test warning from Python")
                print("::notice:: This is a test notice from Python")
                print("::debug:: This is a test debug from Python")
                multiline="""multi
                line
                output"""
                print(multiline)
                with open(os.environ["GITHUB_OUTPUT"], 'a') as fh:
                    print(f"singleline=some message", file=fh)
                    print(f"multiline<<EOF\n{multiline}\nEOF", file=fh)

            - name: Get output from Python
              run: |
                echo "Singleline"
                echo "${{ steps.write.outputs.singleline }}"
                echo
                echo "Multiline"
                echo "${{ steps.write.outputs.multiline }}"