name: Repository via API

on: workflow_dispatch

jobs:
  showcontext:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          set +e
          ls -lA
          ls -lA scripts
          echo done

      - name: Get repo
        env:
          TOK: ${{ secrets.ENT_TOKEN }}
          SRC: scripts/get_def_repo.yml
        run: python3 scripts/get_def_repo.py $TOK $SRC
