name: Test bash func

on:
  workflow_dispatch:
    inputs:
      AAA:
        description: AAA
        type: string
        required: false

jobs:
  test-func:
    name: Test bash func
    runs-on: ubuntu-latest
    steps:
      - run: |
          function getAAA() {
            if [ -z "${{ inputs.AAA }}" ]; then
              echo "AAA is empty"
            else
              echo "AAA is ${{ inputs.AAA }}"
            fi
          }
          # function chkAAA() {
          #   if [ -z "${{ inputs.AAA }}" ]; then
          #     return 1
          #   else
          #     return 0
          #   fi
          # }
          function chkAAA() { [ -z "${{ inputs.AAA }}" ] && return 1 || return 0; }

          getAAA
          if chkAAA; then
            echo "AAA is ${{ inputs.AAA }}"
          else
            echo "AAA is empty"
          fi
