name: Test Environment Approval

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: environment
        type: choice
        required: true
        options:
          - 'UAT'
          - 'PROD'

jobs:
  pre:
    name: Pre
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.actor }}
      - if: ${{ inputs.ENV == 'PROD' }}
        run: echo is PROD

  non-approval:
    if: ${{ inputs.ENV == 'PROD' }}
    name: non approval
    needs: [pre]
    environment: production-abcdef
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.actor }}
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo ${{ github.event.review.user.login }}

  approval:
    if: ${{ inputs.ENV == 'PROD' }}
    name: approval
    needs: [pre]
    environment: production
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.actor }}
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo ${{ github.event.review.user.login }}

  post:
    name: Post
    needs: [approval]
    if: '!cancelled() && !failure()'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.actor }}
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo ${{ github.event.review.user.login }}
