name: Test gh secret set

on: workflow_dispatch

jobs:
  testscr:
    name: Test gh secret set
    runs-on: ubuntu-latest
    steps:
      - name: Test gh secret set
        run: echo "${{ secrets.TESTMULTILINE }}"
