name: test git tags

on:
  workflow_dispatch:
  push:
    branches: main
    paths: .github/workflows/test-gitpush.yml

jobs:
  test-git-tag:
    name: Test git tag
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        # with:
        #   # ref: uat
        #   fetch-depth: 0

      - name: Test commit push
        run: |
          git branch -vv
          git checkout main
          git branch -vv
          echo >> README.md
          git add README.md

          git config user.email "guanpok86@hotmail.com"
          git config user.name "bubutz"

          git commit -m "test commit"
          git push
          git log --oneline | head -3

      # - name: Test new tag
      #   run: |
      #     # git config user.email "guanpok86@hotmail.com"
      #     # git config user.name "bubutz"
      #
      #     BUILD_BRANCH=${{ github.ref }}
      #     echo $BUILD_BRANCH
      #
      #     # Read current ver from version.txt
      #     current_version=$(cat version.txt)
      #     echo current_version = $current_version
      #
      #     # Create a git tag with the current version
      #     tag_exists=$(git tag -l "$current_version")
      #     echo tag_exists = $tag_exists
      #     if [ -n "$tag_exists" ]; then
      #       git tag -d "$current_version" && echo deleted tag
      #       git push -d origin "$current_version" && echo deleted tag
      #       git tag -l
      #     fi
      #     echo ---- start; git tag "$current_version" && echo added tag
      #     git tag -l ; echo ---- end
      #
      #     # push tag to repository
      #     git push origin "$current_version"
      #
      #     # delete branch if exists
      #     if git show-ref -q --heads $BUILD_BRANCH; then
      #       git branch -D $BUILD_BRANCH
      #     fi
      #     git fetch
      #     git switch $BUILD_BRANCH
      #     git pull --no-rebase
      #
      #     # split the version into major, minor and patch components
      #     IFS='.' read -r major minor patch <<< "${current_version//v/}"
      #     echo major $major
      #     echo minor $minor
      #     echo patch $patch
      #
      #     # increment the patch version
      #     patch=$((patch +1))
      #     echo patch $patch
      #
      #     # create the new version string
      #     new_version="v$major.$minor.$patch"
      #     echo new_version $new_version
      #
      #     # update version.txt with new version
      #     echo "$new_version" > version.txt
      #     echo cat version.txt
      #     cat version.txt
      #
      #     # commit change to version.txt
      #     git add version.txt
      #     git commit --author="bubutz <guanpok86@hotmail.com>" -m "Bump version to $new_version"
      #
      #     # push to repo
      #     git push
      #     git checkout "$current_version"


  test-git-tag-noperm:
    name: Test git tag no contents write permissions
    runs-on: ubuntu-latest

    # permissions:
    #   contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        # with:
        #   # ref: uat
        #   fetch-depth: 0

      - name: Test commit push
        run: |
          git branch -vv
          git checkout main
          git branch -vv
          echo >> README.md
          git add README.md

          git config user.email "guanpok86@hotmail.com"
          git config user.name "bubutz"

          git commit -m "test commit"
          git push
          git log --oneline | head -3
