name: test composite shell

on:
  workflow_dispatch: {}
  # push:
  #   branches:
  #     - main
  #     - uat

jobs:
  test-trigger:
    name: Test trigger
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/test-comp-shell@main
