name: test variables

on:
  workflow_dispatch:
  push:
    branches: main
    paths: .github/workflows/*

jobs:
  env-vars:
    name: Set Variables
    runs-on: ubuntu-latest

    steps:
      - name: Set output vars
        id: env_vars
        run: |
          echo ----------------------------------------------------------------
          echo Set Variables
          echo "VAR_A=hello" >> $GITHUB_OUTPUT
          echo "VAR_B=world" >> $GITHUB_OUTPUT

    outputs:
      VAR_A: ${{ steps.env-vars.outputs.VAR_A }}
      VAR_B: ${{ steps.env-vars.outputs.VAR_B }}

  show-job-vars:
    name: Show job vars
    runs-on: ubuntu-latest
    needs: [set-vars]

    env:
      VAR_A: ${{ needs.env-vars.outputs.VAR_A }}
      VAR_B: ${{ needs.env-vars.outputs.VAR_B }}

    steps:
      - name: Output on Job level ENV
        run: |
          echo ----------------------------------------------------------------
          echo Show Variables
          echo VAR_A = $VAR_A
          echo VAR_B = $VAR_B
          echo VAR_A = ${{ needs.env-vars.outputs.VAR_A }}
          echo VAR_B = ${{ needs.env-vars.outputs.VAR_B }}

  show-step-vars:
    name: Show step vars
    runs-on: ubuntu-latest
    needs: [set-vars]

    steps:
      - name: Output on Job level ENV
        env:
          VAR_A: ${{ needs.env-vars.outputs.VAR_A }}
          VAR_B: ${{ needs.env-vars.outputs.VAR_B }}
        run: |
          echo ----------------------------------------------------------------
          echo Show Variables
          echo VAR_A = $VAR_A
          echo VAR_B = $VAR_B
          echo VAR_A = ${{ needs.env-vars.outputs.VAR_A }}
          echo VAR_B = ${{ needs.env-vars.outputs.VAR_B }}

  test-ifs:
    name: Test If Conditions
    runs-on: ubuntu-latest
    needs: [show-job-vars, show-step-vars]
    steps:
      - run: |
          echo ----------------------------------------------------------------
          echo Set Variables
