name: Test CMD Exit

on:
  workflow_dispatch: {}

jobs:
  test-cmd-exit:
    name: Test cmd exit
    runs-on: windows-latest
    steps:
      - shell: cmd
        run: |
          echo ABC
          exit /b 1
          echo DEF
      - run: echo GHI
