name: test api get repo

on: workflow_dispatch

jobs:
  showcontext:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get repo
        env:
          TOK: ${{ secrets.ENT_TOKEN }}
          SRC: script/get_def_repo.yml
        run: python3 scripts/get_def_repo.py $TOK $SRC

