name: test api get repo

on: workflow_dispatch

jobs:
  showcontext:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          TOK: ${{ secrets.ENT_TOKEN }}
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${TOK}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/bubutz/testops

