name: test jdk8

on:
  workflow_dispatch:
  push:
    branches: main
    paths: .github/workflows/test-setupjava.yml

jobs:
  setupjava:
    name: setup java
    runs-on: ubuntu-latest
    container: oraclelinux:8

    steps:

      - run: java -version || java version
      # - uses: oracle-actions/setup-java@v1
      #   with:
      #     website: oracle.com
      #     release: 23
      # - run: java -version || java version
