name: test changeset (filechange)

on:
  workflow_dispatch:
  # push:
  #   branches: main
  #   paths: .github/workflows/test-changeset.yml

jobs:
  getfilechange:
    name: Get file changed
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: files
        uses: tj-actions/changed-files@v45

      - run: printf "%s\n" "${{ steps.files.outputs.all_changed_files }}"

  changeset:
    name: Test Changeset
    runs-on: ubuntu-latest

    if: |
      contains(github.event.head_commit.modified, 'dir1/') ||
      contains(github.event.head_commit.modified, 'file2.txt')

    steps:
      - name: Hit
        run: |
          echo hit

