name: test restful api response

on: workflow_dispatch

env:
  branch_url: "https://api.github.com/repos/bubutz/testops/branches"

jobs:
  showcontext:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get repo
        env:
          TOK: ${{ secrets.ENT_TOKEN }}
        run: |
          echo branch_url == $branch_url
          python3 scripts/ghapi-rest.py $TOK $branch_url
