name: test variables

on:
  workflow_dispatch

jobs:
  set-vars:
    name: Set Variables
    runs-on: ubuntu@latest
    steps:
      - run: |
          echo ----------------------------------------------------------------
          echo Set Variables

  show-vars:
    name: Show Variables
    runs-on: ubuntu@latest
    needs: [set-vars]
    steps:
      - run: |
          echo ----------------------------------------------------------------
          echo Set Variables

  test-ifs:
    name: Test If Conditions
    runs-on: ubuntu@latest
    needs: [test-ifs]
    steps:
      - run: |
          echo ----------------------------------------------------------------
          echo Set Variables
