name: Test gh secret set

on: workflow_dispatch

jobs:
  testscr:
    name: Test gh secret set
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.TESTMULTILINE }}" > tmp1.txt
      - run: cat tmp1.txt
