name: test variables

on:
  workflow_dispatch:
  push:
    branches: main
    paths: .github/workflows/*

jobs:
  set-vars:
    name: Set Variables
    runs-on: ubuntu_latest
    steps:
      - run: |
          echo ----------------------------------------------------------------
          echo Set Variables

  show-vars:
    name: Show Variables
    runs-on: ubuntu_latest
    needs: [set-vars]
    steps:
      - run: |
          echo ----------------------------------------------------------------
          echo Set Variables

  test-ifs:
    name: Test If Conditions
    runs-on: ubuntu_latest
    needs: [show-vars]
    steps:
      - run: |
          echo ----------------------------------------------------------------
          echo Set Variables
