name: test changeset (filechange)

on:
  workflow_dispatch:
  push:
    branches: main
    paths: .github/workflows/test-changeset.yml

jobs:
  changeset:
    name: Test Changeset
    runs-on: ubuntu-latest

    if: |
      contains(github.event.head_commit.message, 'dir/') ||
      contains(github.event.head_commit.message, 'file2.txt')

    steps:
      - name: Hit
        run: |
          echo hit

