name: test changeset (filechange)

on:
  workflow_dispatch:
  # push:
  #   branches: main
  #   paths: .github/workflows/test-changeset.yml

jobs:
  changeset-hit:
    name: Test Changeset Hit
    runs-on: ubuntu-latest

    if:

    permissions:
      contents: write

    steps:
      # - name: Checkout Repo
      #   uses: actions/checkout@v4
      #   with:
      #     # ref: uat
      #     fetch-depth: 0

      # - name: Test commit push
      #   run: |
      #     git branch -vv
      #     git checkout main
      #     git branch -vv
      #     echo >> README.md
      #     git add README.md
      #
      #     git config user.email "guanpok86@hotmail.com"
      #     git config user.name "bubutz"
      #
      #     git commit -m "test commit"
      #     git push
      #     git log --oneline | head -3

