name: test general

on:
  workflow_dispatch:
  push:
    branches: main
    paths: .github/workflows/test-general.yml


jobs:
  general-test:
    name: General test
    runs-on: ubuntu-latest

    steps:
      - name: check .ssh
        run: |
          ls -lAR .ssh
