name: test variables

on:
  workflow_dispatch:
  push:
    branches: main
    paths: .github/workflows/*

jobs:
  vars:
    name: Set Variables
    runs-on: ubuntu-latest

    steps:
      - name: Set output vars
        id: env_vars
        run: |
          echo ----------------------------------------------------------------
          echo Set Variables
          echo "VAR_A=hello" >> $GITHUB_OUTPUT
          echo "VAR_B=world" >> $GITHUB_OUTPUT

    outputs:
      VAR_A: ${{ steps.env_vars.outputs.VAR_A }}
      VAR_B: ${{ steps.env_vars.outputs.VAR_B }}

  show-job-vars:
    name: Show job vars
    runs-on: ubuntu-latest
    needs: [env-vars]

    env:
      VAR_A: ${{ needs.vars.outputs.VAR_A }}
      VAR_B: ${{ needs.vars.outputs.VAR_B }}

    steps:
      - name: Output on Job level ENV
        run: |
          echo ----------------------------------------------------------------
          echo Show Variables
          echo \$VAR_A = $VAR_A
          echo \$VAR_B = $VAR_B
          echo \${{ env.VAR_A }} = ${{ env.VAR_A }}
          echo \${{ env.VAR_B }} = ${{ env.VAR_B }}
          echo needs.VAR_A = ${{ needs.vars.outputs.VAR_A }}
          echo needs.VAR_B = ${{ needs.vars.outputs.VAR_B }}

  show-step-vars:
    name: Show step vars
    runs-on: ubuntu-latest
    needs: [env-vars]

    steps:
      - name: Output on Job level ENV
        env:
          VAR_A: ${{ needs.vars.outputs.VAR_A }}
          VAR_B: ${{ needs.vars.outputs.VAR_B }}
        run: |
          echo ----------------------------------------------------------------
          echo Show Variables
          echo \$VAR_A = $VAR_A
          echo \$VAR_B = $VAR_B
          echo \${{ env.VAR_A }} = ${{ env.VAR_A }}
          echo \${{ env.VAR_B }} = ${{ env.VAR_B }}
          echo needs.VAR_A = ${{ needs.vars.outputs.VAR_A }}
          echo needs.VAR_B = ${{ needs.vars.outputs.VAR_B }}

  test-ifs-steps:
    name: Test If Conditions
    runs-on: ubuntu-latest
    needs: [show-job-vars, show-step-vars]

    steps:
      - name: Setup vars
        id: lvars
        env:
          VAR_A: ${{ needs.vars.outputs.VAR_A }}
          VAR_B: ${{ needs.vars.outputs.VAR_B }}
        run: |
          echo "VAR_A=${VAR_A}" >> $GITHUB_ENV
          echo "VAR_B=${VAR_B}" >> $GITHUB_ENV

      - name: If miss
        if: needs.env-vars.outputs.VAR_A == "helloooo"
        run: |
          echo VAR_A $VAR_A
          echo VAR_B $VAR_B
          echo MISSSSS

      - name: If hit
        if: needs.env-vars.outputs.VAR_A == "hello"
        run: |
          echo VAR_A $VAR_A
          echo VAR_B $VAR_B
          echo OK
