name: test api get repo

on: workflow_dispatch

jobs:
  showcontext:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get repo
        env:
          TOK: ${{ secrets.ENT_TOKEN }}
          ORG: bubutz
          REPO: testops
        run: python3 scripts/get_def_repo.py $TOK $ORG $REPO
