name: test changeset (filechange)

on:
  workflow_dispatch:
  # push:
  #   branches: main
  #   paths: .github/workflows/test-changeset.yml

jobs:
  changeset:
    name: Test Changeset
    runs-on: ubuntu-latest

    if: |
      contains(github.event.head_commit.modified, 'dir1/') ||
      contains(github.event.head_commit.modified, 'file2.txt')

    steps:
      - name: Hit
        run: |
          echo hit

