name: Test gh secret set

on:
  workflow_dispatch:
    inputs:
      org_name:
        description: 'Org name'
        type: choice
        required: true
        options:
          - all
          - org1
          - org2
          - org3
          - org4
      secret_name:
        description: 'Secret name'
        required: true
      secret_value:
        description: 'Secret value'
        required: true
      base64:
        description: 'Base64 secrets?'
        type: choice
        required: true
        default: yes
        options:
          - yes
          - no

jobs:
  testscr:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Mask values
        run: |
          secret_value="$(jq -r '.inputs.secret_value' $GITHUB_EVENT_PATH)"
          echo ::add-mask::$secret_value
          echo secret_value=$secret_value >> $GITHUB_ENV

      - run: echo "${{ env.secret_value }}" | sed 's/./& /g'
      - name: Test values
        run: |
          if [ "${{ inputs.base64 }}" = "true" ]; then
              secret_v="$(echo ${{ env.secret_value }} | base64 --decode)"
              echo "::add-mask::$secret_v"
              echo "mask done"
              echo _____________________________________________________
          fi
          if [ "${{ inputs.org_name }}" = "all" ]; then
              ORGS="org1 org2 org3 org4"
              for ORG in $ORGS; do
                  if [[ "$ORG" == "org2" || "$ORG" == "org4" ]]; then
                      continue
                  fi
                  echo Secret ${{ inputs.secret_name }} setup for $ORG
                  echo "Input value is \"$secret_v\""; echo
              done
          else
              echo Secret ${{ inputs.secret_name }} setup for ${{ inputs.org_name }}
              echo "Input value is \"$secret_v\""; echo
          fi
          echo; echo _____________________________________________________
          echo "$secret_v" | sed 's/./& /g'
