name: test variables

on:
  workflow_dispatch:
  push:
    branches: main
    paths: .github/workflows/test-gitpush.yml

permissions:
  contents: write

  test-git-tag:
    needs: vars
    name: Test git upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Test upload new commit
        run: |
          echo draft
