name: test api get rule

on: workflow_dispatch

jobs:
  showrules:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event.repository.default_branch) }}"
      - name: Get repo
        env:
          TOK: ${{ secrets.ENT_TOKEN }}
          ORG: bubutz
          REPO: testops
        run: python3 scripts/get_def_repo.py $TOK $ORG $REPO
