name: test variables

on:
  workflow_dispatch:
  push:
    branches: main
    paths: .github/workflows/*

env:
  AA: aaa
  BB: bbb

jobs:
  if-with-global-env:
    name: Set Variables
    runs-on: ubuntu-latest

    steps:
      - name: Always run
        run: echo Always run

      - name: If fail
        # if: env.AA == 'aaaa'
        run: echo Should not run

      - name: If pass
        # if: env.AA == 'aaaa'
        run: echo Should run

  vars:
    needs: [if-with-global-env, if-with-local-env]
    name: Set Variables
    runs-on: ubuntu-latest

    steps:
      - name: Set output vars
        id: env_vars
        run: |
          echo Set Variables
          echo "VAR_A=hello" >> $GITHUB_OUTPUT
          echo "VAR_B=world" >> $GITHUB_OUTPUT

    outputs:
      VAR_A: ${{ steps.env_vars.outputs.VAR_A }}
      VAR_B: ${{ steps.env_vars.outputs.VAR_B }}

  show-job-vars:
    needs: [vars]
    name: Show job vars
    runs-on: ubuntu-latest

    env:
      VAR_A: ${{ needs.vars.outputs.VAR_A }}
      VAR_B: ${{ needs.vars.outputs.VAR_B }}

    steps:
      - name: Output on Job level ENV
        run: |
          echo Show Variables
          echo \$VAR_A = $VAR_A
          echo \$VAR_B = $VAR_B
          echo \${{ env.VAR_A }} = ${{ env.VAR_A }}
          echo \${{ env.VAR_B }} = ${{ env.VAR_B }}
          echo needs.VAR_A = ${{ needs.vars.outputs.VAR_A }}
          echo needs.VAR_B = ${{ needs.vars.outputs.VAR_B }}

  show-step-vars:
    needs: [vars]
    name: Show step vars
    runs-on: ubuntu-latest

    steps:
      - name: Output on Job level ENV
        env:
          VAR_A: ${{ needs.vars.outputs.VAR_A }}
          VAR_B: ${{ needs.vars.outputs.VAR_B }}
        run: |
          echo Show Variables
          echo \$VAR_A = $VAR_A
          echo \$VAR_B = $VAR_B
          echo \${{ env.VAR_A }} = ${{ env.VAR_A }}
          echo \${{ env.VAR_B }} = ${{ env.VAR_B }}
          echo needs.VAR_A = ${{ needs.vars.outputs.VAR_A }}
          echo needs.VAR_B = ${{ needs.vars.outputs.VAR_B }}

  test-ifs:
    needs: [show-job-vars, show-step-vars]
    name: Test If Conditions
    runs-on: ubuntu-latest

    # env:
      # VAR_A: ${{ needs.vars.outputs.VAR_A }}
      # VAR_A: hello
      # VAR_B: ${{ needs.vars.outputs.VAR_B }}

    steps:
      - name: Setup Env
        run: |
          echo needs.VAR_A = ${{ needs.vars.outputs.VAR_A }}
          echo needs.VAR_B = ${{ needs.vars.outputs.VAR_B }}
          echo "VAR_A=${{ needs.vars.outputs.VAR_A }}" >> $GITHUB_OUTPUT
          echo "VAR_B=${{ needs.vars.outputs.VAR_B }}" >> $GITHUB_OUTPUT

      - name: If hit
        # if: env.VAR_A == "hello"
        run: |
          echo VAR_A $VAR_A
          echo VAR_B $VAR_B
          echo OK

      - name: If miss
        # if: env.VAR_A == "helloooo"
        run: |
          echo VAR_A $VAR_A
          echo VAR_B $VAR_B
          echo MISSSSS
