name: test variables

on:
  workflow_dispatch:
  push:
    branches: main
    paths: .github/workflows/*

jobs:
  set-vars:
    name: Set Variables
    runs-on: ubuntu-latest
    id: vars

    steps:
      - run: |
          echo ----------------------------------------------------------------
          echo Set Variables
          echo "VAR_A=hello" >> $GITHUB_OUTPUT
          echo "VAR_B=world" >> $GITHUB_OUTPUT

    outputs:
      VAR_A: "${{ steps.vars.outputs.VAR_A }}"
      VAR_B: "${{ steps.vars.outputs.VAR_B }}"

  show-vars:
    name: Show Variables
    runs-on: ubuntu-latest
    needs: [set-vars]

    steps:
      - run: |
          echo ----------------------------------------------------------------
          echo Show Variables
          echo VAR_A = "${{ needs.vars.outputs.VAR_A }}"
          echo VAR_B = "${{ needs.vars.outputs.VAR_B }}"

  test-ifs:
    name: Test If Conditions
    runs-on: ubuntu-latest
    needs: [show-vars]
    steps:
      - run: |
          echo ----------------------------------------------------------------
          echo Set Variables
